### ISSUE TITLE
 Unknown socket option TCP_NODELAY IPTOS_LOWDELAY

### ISSUE THREAD

**Issue by Hadatko** [ServerContainers/samba#100]
Hi. Thank you for your container. During booting container i am getting several errors:

[2023/08/16 22:09:32.903988,  0] ../../lib/util/util_net.c:1045(set_socket_options)
  Unknown socket option TCP_NODELAY IPTOS_LOWDELAY
  
  Here i can be more descriptive. I think we are missing include file. My environment variable looks like:
  `- SAMBA_GLOBAL_CONFIG_socket_SPACE_options="TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072"`
  
  I need to find out if it is related to this or it is related to samba error:
  ou may find that on some systems Samba will say "Unknown socket option" when you supply an option. This means you either incorrectly typed it or you need to add an include file to includes.h for your OS. If the latter is the case please send the patch to [samba-technical@lists.samba.org](mailto:samba-technical@lists.samba.org).

**Comment by MarvAmBass** [comment]
Hi there, yeah I also noticed this. but it seemed to me to be an samba build issue.

since I'm no longer building samba from scratch (I used to do this in the earlier times of this container) I totally rely on the alpine samba build.

Since this build might be stripped down, and I didn't have any problems with it I just ignored it.

this repo is not the right place for such an issue - it wouldn't be different to an alpine linux with installed samba package
