### ISSUE TITLE
Cannot use UID and GID of a host user

### ISSUE THREAD

**Issue by sanyer** [ServerContainers/samba#120]
First of all, thank you very much, it is a nice and easy to use samba container.

However, I need to use the same gid as my host files in order to allow various users to write to folder mounted to container.
And container is currently failing to create the user required.

**My setup:**
- Raspberry Pi Debian
- user:group - pi:pi - 1000:1000
- docker-compose.yaml
      
        ...
        GROUP_family: 1000
        ACOCUNT_mark: mark
        UID_mark: 1000
        GROUPS_mark: family
        ...

**Expected behavior:**
User mark (1000) created and added to group family (1000).

**Actual behavior:**
User mark (1000) is not created. Group family (1000) is created.

**Extra information:**
I did some basic debugging and found that the line https://github.com/ServerContainers/samba/blob/4d5796dd064a69ea31eb860046c4a7391ef40844/scripts/entrypoint.sh#L115 creates user mark (1000) with his own group mark (1000), but since family (1000) group already exists this command fails.

I was able to manually create user mark using this command `adduser -G family -D -H -u 1000 rzhuzha`. This doesn't create group mark, but does allow me to connect to the share properly.

**Comment by MarvAmBass** [comment]
yeah you're right in your example user mark gets 1000 as uid and gid - I think that specifing `UID_mark` is unnessecary since the first user gets `1000` anyways.

take a look at your configuration - you use the pi user with it's default group pi -> 1000:1000
and you create your user mark inside the container with his default group -> 1000:1000

and then you specify a group with a groupid collision - this doesn't make sense

my recommendation:

- create a group on host and inside the container - those should share the same group id
- if user pi needs also group access, ad him to this new group

keep in mind, groups are for grouping! and user groups are user groups - I would not advice to use them for grouping together multiple users.

also you might want to fix the group permissions on the share - it seems to me, that it doesn't make sense to have the folders group set to a users group if you want multiple users to have access to it

**Comment by sanyer** [comment]
Yeah, all worked now, don't know what I was thinking back then. Perhaps it was a tough day and my brain shut down :-D
Thanks for being patient.
