### ISSUE TITLE
differnce to dperson/samba

### ISSUE THREAD

**Issue by Silther** [ServerContainers/samba#121]
what is the difference between this samba docker and the older one from https://github.com/dperson/samba?

**Comment by MarvAmBass** [comment]
mine is actively maintained - dperson/samba doesn't seem to be maintained and has no changes within the last 4 years - so I'd say with mine you get the latest version

also I have a different concept of how things should be done, there are different flavors of my container, also autobuilds and version of not only samba, but the other services and the base system

since dperson/samba seems to be no longer actively maintained, I'd advice to no longer use this container - unless you put some work into it, build it yourself and maybe make some upgrades
