### ISSUE TITLE
Use GitHub Actions to build docker images instead of local builds/ServerContainers

### ISSUE THREAD

**Issue by rursache** [ServerContainers/samba#77]
You should use GitHub Actions to build docker images instead of local builds/ServerContainers. It's free and linked to the repo

**Comment by MarvAmBass** [comment]
Hi thanks for the hint, but since docker hub is closing on small open source organisations like `servercontainers`, it does no longer matter.

I've just updated the build script, that anyone can build and push into their own registries.

**Comment by rursache** [comment]
Example of docker hub + github registry usage - https://github.com/crazy-max/docker-samba

**Comment by MarvAmBass** [comment]
It seems you didn't understand the problem, there is no place where I could safely store my images.
the servercontainers space will be removed by docker.

so I could build those images automatically, even with github, but all users need to migrate anyway.

**Comment by rursache** [comment]
Indeed i don't understand, just create a personal github account and move the work there incl. building the image. A one time migration is not a problem, building the docker image each time a new update comes up is.

**Comment by le-ander** [comment]
I think the point @rursache is trying to make is that you could simply migrate from storing your images on docker hub to storing them on the github container registry and automate the whole build and release process using github actions. This way you won't depend on docker hub anymore and users could just pull your prebuilt images as their used to, using something like:

```
docker pull ghcr.io/ServerContainers/samba:latest
```

https://github.blog/2020-09-01-introducing-github-container-registry/

It'd definitely be super convenient for users not having to manage their own registry in order to still be able to use this great container :)

**Comment by rursache** [comment]
exactly what @le-ander said but I assumed @MarvAmBass you knew about the github registry and actions. its really a easy migration to github registry.

**Comment by MarvAmBass** [comment]
Hi there, I was working this weekend on a solution which is able to build/push to any registry.

I honestly didn't know about the registry 🙈  I just knew, and used to use the github actions.
If that's the case I'll look into it, and might add said triggers.

I'll reopen the ticked and keep you guys updated. we have a few more days until the docker registry closes

**Comment by MarvAmBass** [comment]
ohhh wow it's even possible to migrate all images <3

**Comment by labodj** [comment]
> docker pull ghcr.io/servercontainers/samba:a3.17.2-s4.16.8-r1

It seems that this ghcr repo is private, can you make it public?

```
docker pull ghcr.io/servercontainers/samba:a3.17.2-s4.16.8-r1
Error response from daemon: Head "https://ghcr.io/v2/servercontainers/samba/manifests/a3.17.2-s4.16.8-r1": unauthorized

docker pull ghcr.io/servercontainers/samba
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/servercontainers/samba/manifests/latest": unauthorized
```

**Comment by MarvAmBass** [comment]
now it's public - interessting, that it's limited to private on org level :)

**Comment by MarvAmBass** [comment]
Hi everyone, thanks for your hints and support - if I just knew about the github registry earlier 🤦 

The migration of the samba container should be done now. It's even better since there is a daily build - so we won't miss any version updates. Note that tags do not get overwritten :)

I'll close this issue now. (if you use other containers of my orgs, I'll move them within the next days :))
