### ISSUE TITLE
Daily image updates

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [ServerContainers/samba#88]
I get an image update notification every single day.
Is there a reason this image gets updated so often? Does anything change at all?

**Comment by MarvAmBass** [comment]
thanks, usually nothing should change - a daily build is configured that it notes when there is a new version and creates one with a new tag.

maybe I can improve this a bit, but I'm not sure how at the moment

let me now if you have a neaty idea

**Comment by MarvAmBass** [comment]
also how do you get those notifications? I didn't know one can subscribe to notifications

**Comment by Unkn0wn-MDCLXIV** [comment]
I’m using diun to get notified when there is a new image for my containers available.

It depends on when you need to build a new image - when there are changes to the repo? When there are changes to the base image / packages?

**Comment by MarvAmBass** [comment]
yeah exactly, that's why lastest is kinda unstable. I build it to get all the alpine updates - this container is very small but even the side packages might benefit from getting updates everyday.

there is nothing worse than a container with outdated, maybe toxic userland tools

I'll take a look at `diun`

**Comment by techsolo12** [comment]
I also have the same problem as @Unkn0wn-MDCLXIV. I use `diun` for notification about new updates. When a new image is released on repository, a got notification over pushover with the link to the repo. So i can check quickly the new release notes.
In addition to `diun` i use `watchtower`. Watchtower is perfect for auto-update images and rebuilding containers with a new released image. Also, watchtower send me a notification over pushover with the status of how the update processes runs. Runs a update bad, i restore manually the backup from before the update and block the update to the new version.

So i get every day min. two notifications for the daily build action of this repo. I understand that you don't want to wait for major releases or minor release of alpine to do a new build, but is every little packet needed? Do you think it's possible to reduce this action to one time a week? Don't understand me wrong, i don't want to moan or something else, it's my problem, but it will help some people a lot, i think.

**Comment by MarvAmBass** [comment]
I fully understand you guys!

It's not the best possible solution yet.

See, in a perfect world I'd only update if some libraries, samba or repo changes occurred.

Also note that we've come a long way - in the beginning of this container (more than 5 years ago) there was only the lastest Tag - and if it was broken nobody was able to use it 😂🙈

I also see that I should invest a bit time since this container is so successful and has so many users.

Thanks for your hints about this two applications, I might look into them and try to optimize my workflow 

Maybe I find a good and better way working with tags.


Things I think are important:

### 1
It should not break user setups

### 2
It's not feasible to ignore updates of other system packages - once we start to ignore stuff we need to do risk assessments and evaluation if it really has no security impact.

That's why I try to have everything super small and not many unnecessary packages installed 
And also keep this minimal installation updated as a whole thing



I'll think about all that and maybe I come to a new solution 👍

**Comment by MarvAmBass** [comment]
hi everyone, I guess I found a quick and neat solution.

the samba build will now fail if the tag combination is already present - this should skip the daily builds, and make only those available which lead to a unbuild number.

I'll have to think how to handle manuall updates (if I fix a build and want to force the release/overwrite a current tag) but this is another story... I'll close this for now, since there are no longer daily builds and spammy latest tags :)

**Comment by techsolo12** [comment]
@MarvAmBass Perfect! Thank you very much! No annoying unneeded notifications anymore. :)

**Comment by Unkn0wn-MDCLXIV** [comment]
Has something changed? I'm receiving daily updates again.

**Comment by MarvAmBass** [comment]
Hi there,

I've updated my scripts to no longer fail but skip the building if no image build is needed, I just checked and it seems like you're right - it builds daily now - I take a look and hopefully find a fix :)

**Comment by MarvAmBass** [comment]
I've just added some fixes - hope it works - I really hate github workflows :D - gitlab ci is sooo much cleaner

**Comment by MarvAmBass** [comment]
issue resolved
