### ISSUE TITLE
Samba is discoverable by Windows but not discoverable by another Linux machine

### ISSUE THREAD

**Issue by ypj0202** [ServerContainers/samba#91]
As mentioned in the title, it is discoverable and accessible by other Windows machine with `wsdd` enabled. However, other Linux machine is not cannot discover it (But can access via IP) even `avahi` service is running on the host with no errors. \
Host: Raspberry Pi 4
OS: Debian 11
Used version: a3.18.0-s4.18.2-r0
Network mode: Host

**Comment by MarvAmBass** [comment]
can you check if your avahi configuration is exposing the samba server?

it might be a problem if the host also runs an avahi server - please mount the configuration folder of avahi so that the container can add it's avahi samba config. avahi server restart is required after the config was placed.

also you can check with an avahi/zeroconf explorer tool (there are tools and even apps available which can show everything which is exposed within your network)

also make sure, that avahi only works within one network and is not routed!

hope those hint's help you

**Comment by LeChatP** [comment]
Same here; I can't discover my RPI4B from Kodi.
It works if the network is done manually.

**Comment by Hadatko** [comment]
Same with me. It worked in past, but i was changing hw and OS and now it is not working. (previously i had samba installation also in OS, not sure if that can be related)

**Comment by MarvAmBass** [comment]
what OS are you using now? do you start with host avahi or container avahi?

**Comment by MarvAmBass** [comment]
I've made some updates, previously avahi wasn't configured when there was no timemachine share available - this should be now resolved. It might have a positive impact on this issue as well

**Comment by LeChatP** [comment]
Issue seems to be still present,
tested on arm64: latest@sha256:6a9edb840077707afaab565a7b919cd20eee857f985b2d94c33cb589d54b8c17

**Comment by MarvAmBass** [comment]
I got a new pull request which added `nmbd` I ignored it cause I thougt it's a compatibility layer which only legacy systems relay on.

but it seems like it helped the guy who did the pull request with similar issues, as you're facing!

**Comment by LeChatP** [comment]
Issue Solved with sha256:0f8e795f96940e61eeeaa9feea7ec21c8ecb7d12bd0f6ce7701ca1c3e762d71d !
Thank you very much!

**Comment by MarvAmBass** [comment]
I'll close this issue than - makes sense that the missing `nmbd` was the root of this problem - can't believe I didn't think about that 😄  sometime you miss the most obvious things 🤦 

@jfhenriques thanks for taking the time of looking into this container and fixing this issue!
