### ISSUE TITLE
 pid_to_procid: messaging_dgm_get_unique failed: No such file or directory

### ISSUE THREAD

**Issue by Hadatko** [ServerContainers/samba#98]
Hi. Thank you for your container. During booting container i am getting several errors:

[2023/08/16 22:10:43.502286,  3] ../../source3/lib/util_procid.c:53(pid_to_procid)
  pid_to_procid: messaging_dgm_get_unique failed: No such file or directory

**Comment by MarvAmBass** [comment]
I suspect this is an issue of samba running inside the container, or because some features are missing in the alpine build. as long as there are no negative consequences there is no time to investigate this further.

If you have time and find the problem + solution I'm happy to fix this - if possible on my container level. build problems need to be addressed on the alpine build level

I'm closing this since for now it's just an odd log message
