### ISSUE TITLE
   tdb(/var/lib/samba/registry.tdb): tdb_open_ex: could not open file /var/lib/samba/registry.tdb: No such file or directory

### ISSUE THREAD

**Issue by Hadatko** [ServerContainers/samba#99]
Hi. Thank you for your container. During booting container i am getting several errors:

[2023/08/16 22:10:43.506661,  2] ../../lib/tdb_wrap/tdb_wrap.c:65(tdb_wrap_log)
  tdb(/var/lib/samba/registry.tdb): tdb_open_ex: could not open file /var/lib/samba/registry.tdb: No such file or directory

**Comment by MarvAmBass** [comment]
your welcome, thanks for raising these issues, I've also noticed those and other strange/wierd log messages. but they come and go. depends on samba package version. so I think it's not really a problem of the container or its generated samba config. 
please note, that maintaining a container which such a huge userbase is super super time consuming for a guy who does this in is spare time. if you can pin this log message to a specific not working behavior or problem I might take some time to investigate - but right now most of the features, even fancy ones work properly.

If there is even a small issue I get an issue right away 😆 

Also this container doesn't have it's focus on huge enterprise environments with active directory and group directory stuff. I suspect that it still works in most cases, but if you want to do super fancy stuff, or make an AD controller out of this container you might run into issues - I think most of those fancy log messages are hints that it would have troubles in an controller mode of some sort.

other than that:

I suspect this is an issue of samba running inside the container, or because some features are missing in the alpine build. as long as there are no negative consequences there is no time to investigate this further.

If you have time and find the problem + solution I'm happy to fix this - if possible on my container level. build problems need to be addressed on the alpine build level

I'm closing this since for now it's just an odd log message
